apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-portfolio
  labels:
    app: ui-portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-portfolio
  template:
    metadata:
      labels:
        app: ui-portfolio
    spec:
      containers:
        - name: ui-portfolio
          image: docker.io/quochau151/ui_portfolio:latest
---
apiVersion: v1
kind: Service
metadata:
  name: ui-portfolio-service
spec:
  selector:
    app: ui-portfolio
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
